[2023-03-27T03:10:25.702+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data scheduled__2023-03-18T00:00:00+00:00 [queued]>
[2023-03-27T03:10:25.712+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: projeto_agro.extract_data scheduled__2023-03-18T00:00:00+00:00 [queued]>
[2023-03-27T03:10:25.713+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:10:25.713+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-03-27T03:10:25.713+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-03-27T03:10:25.727+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-18 00:00:00+00:00
[2023-03-27T03:10:25.732+0000] {standard_task_runner.py:55} INFO - Started process 107 to run task
[2023-03-27T03:10:25.736+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'projeto_agro', 'extract_data', 'scheduled__2023-03-18T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpky_9ehrz']
[2023-03-27T03:10:25.737+0000] {standard_task_runner.py:83} INFO - Job 82: Subtask extract_data
[2023-03-27T03:10:25.823+0000] {task_command.py:389} INFO - Running <TaskInstance: projeto_agro.extract_data scheduled__2023-03-18T00:00:00+00:00 [running]> on host 264f1e537a4a
[2023-03-27T03:10:26.044+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=projeto_agro
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-18T00:00:00+00:00
[2023-03-27T03:10:43.076+0000] {logging_mixin.py:137} WARNING - /opt/airflow/dags/../../scripts/extract.py:27 DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
[2023-03-27T03:10:43.164+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/main.py", line 16, in extract
    extract.save_data_raw()
AttributeError: 'Extract' object has no attribute 'change_columns_year'
[2023-03-27T03:10:43.184+0000] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=projeto_agro, task_id=extract_data, execution_date=20230318T000000, start_date=20230327T031025, end_date=20230327T031043
[2023-03-27T03:10:43.208+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 82 for task extract_data ('Extract' object has no attribute 'change_columns_year'; 107)
[2023-03-27T03:10:43.269+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-03-27T03:10:43.294+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
